apiVersion: v1
kind: Service
metadata:
  name: chaos-app
  namespace: chaos-canary
spec:
  selector:
    app: chaos-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
